server:
  port: 8093
#   로그 적용 X
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    로그 적용 O
#    url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring :
  profiles:
    active: dev
  datasource :
    url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: postgres
    password: 1234
    initialization-mode: always
#  sql:
#    init:
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql
#      mode: always
  jwt:
    secret: 9622e00b991444795129570113f5d946c8a2d3d00ae04547465aa0790bd412a9
    refreshSecret: 7ca5b2940efa9e6ed776a10074c9b13c468c634de7faedc7cc5ebcd3aaa9a2d5
  jpa:
#    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: none
    properties:
      hibernate:
#        format_sql: true
  http:
    multipart:
      enabled: false
  servlet:
    multipart:
      enabled: true
      location: D:/project-repository/temp
      max-request-size: 10MB
      max-file-size: 10MB
part4:
  upload:
    path: D:/project-repository/

mybatis:
  type-aliases-package: com.app.avengers.DJMT.dto
#  configuration:
#    map-underscore-to-camel-case: true

logging:
  level:
    root: info

file:
  volume-path:
  file-path:
  repository: D:\project-repository

vworld:
  secretkey: 38DFA757-E21B-37A4-ACF1-E9A3FB309B38