DROP TABLE IF EXISTS MEMBER;
-- 회원 테이블
CREATE TABLE MEMBER (
	MEM_NO VARCHAR(40) PRIMARY KEY,
	LOGIN_ID VARCHAR(20) unique,
	LOGIN_PW VARCHAR(100),
	role VARCHAR(10), -- 권한(ADMIN,MEMBER 구분 값)
	MEM_NAME VARCHAR(30),
	MEM_ADDR1 VARCHAR(50),
	MEM_ADDR2 VARCHAR(20),
	MEM_STATUS CHAR(1) , -- 회원 상태 :: 1 가입 0 휴면 99 탈퇴?
	MEM_TEL VARCHAR(20),
	MEM_GEN CHAR(1),
	MEM_BIRTH VARCHAR(8),
	MEM_BIRTH_YN CHAR(1),
	MEM_PROFILE VARCHAR(100),
	REG_ID VARCHAR(40), -- 생성한 회원
	REG_DATE VARCHAR(30), -- 생성 날짜
	CHG_ID VARCHAR(40), -- 변경한 회원
	CHG_DATE VARCHAR(30) -- 변경 날짜
);

DROP TABLE IF EXISTS REFRESHTOKEN;
-- 리프레시 토큰 테이블
CREATE TABLE REFRESHTOKEN (
	REFRESHTOKEN_ID varchar(40) primary key,
	REFRESHTOKEN varchar(255) NULL,
	MEM_NO varchar(40) NULL
);
DROP TABLE IF EXISTS MEM_HIST;
-- 회원 로그인 기록 테이브
CREATE TABLE MEM_HIST(
    MEM_NO VARCHAR(40) PRIMARY KEY,
    REG_ID VARCHAR(40),
    LOGIN_DATE VARCHAR(40),
    LOGOUT_DATE VARCHAR(40)
);

DROP TABLE IF EXISTS FILE_META;
CREATE TABLE FILE_META(
	FILE_ID VARCHAR(40) PRIMARY KEY,
	FILE_NAME VARCHAR(40),
	FILE_ORGNAME VARCHAR(40),
	FILE_PATH VARCHAR(40),
	VOL_TYPE VARCHAR(40),
	DEL_YN VARCHAR(3),
	REG_ID VARCHAR(40),
	REG_DATE VARCHAR(40),
	CHG_ID VARCHAR(40),
	CHG_DATE VARCHAR(40)
);

DROP TABLE IF EXISTS FILE_VOLUME;
CREATE TABLE FILE_VOLUME (
	VOL_ID VARCHAR(40) PRIMARY KEY,
	VOL_TYPE VARCHAR(40),
	VOL_PATH VARCHAR(40)
);